33

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -92,6 +92,22 @@ commands:
                     echo $status
                     echo $result_id
                     echo "test2"
+                    if [[ $result_id -gt 0 ]]
+                    then
+                        echo "$duration"
+                        echo "22Stress $ST_ID has been run; result is $result_id"
+                    else
+                        echo "ERROR running Stress $ST_ID"
+                        exit 403
+                    fi
+                    if [[ $status -gt 0 ]] && [[ $result_id -gt 0 ]]
+                    then
+                        echo "$duration"
+                        echo "33Stress $ST_ID has been run; result is $result_id"
+                    else
+                        echo "ERROR running Stress $ST_ID"
+                        exit 403
+                    fi
             - persist_to_workspace:
                 root: .
                 paths:
