completed0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -111,13 +111,40 @@ commands:
                 name: Check Stress Test results
                 command: |
                     source env.vars
-                    echo "stress test result $Result_ID for original $ST_ID checking"
                     echo "duration: $duration"
-                    resp=$(curl -sb -X GET https://api.dotcom-monitor.com/config_api_v1/StressTest/$Result_ID/Result \
-                        --cookie dm.auth \
-                        -H "Content-Type: application/json")
-                    echo $resp
-
+                    total=$((duration+600))
+                    current=0
+                    found=0
+                    while [[ $current -lt $total ]]
+                    do
+                        if [[ $current -le $duration ]]
+                        then
+                            sleep 120s
+                            current=$((curent+120))
+                        else
+                            sleep 60s
+                            current=$((curent+60))
+                        fi
+                        echo "$(date): stress test result $Result_ID for original stress $ST_ID checking"
+                        resp=$(curl -sb -X GET https://api.dotcom-monitor.com/config_api_v1/StressTest/$Result_ID/Result \
+                            --cookie dm.auth \
+                            -H "Content-Type: application/json")
+                        status=$(echo $resp | grep -o '"StatusDesc":"[A-z]*' | grep -o '[^:]*$')
+                        status_code=$(echo $resp | grep -o '"StatusCode":[0-9]*' | grep -o '[^:]*$')
+                        has_data=$(echo $resp | grep -o '"HasData":[a-z]*' | grep -o '[^:]*$')
+                        echo "results: $status; $status_code; $has_data"
+                        if [[ $status = "Completed" ]] && [[ $has_data = "true" ]]
+                        then
+                            found=1
+                            current=$total 
+                        fi
+                    done
+                    if [[ $fount -eq 1 ]]
+                    then echo "completed!"
+                    else
+                        echo "ERROR stress $Result_ID failed"
+                        exit 500
+                    fi
 jobs:
   build:
     docker:
